### ISSUE TITLE
Support using ConnWithContext in *Script type

### ISSUE THREAD

**Issue by johanbrandhorst** [opencensus-integrations/redigo#6]
Hi! Just found this project. Great stuff!

Something I think it could benefit from is adding support for using a `ConnWithContext` to the `Script` type, so that `(*Script).Do(c Conn)` can automatically use a ConnWithContext if the input Conn implements it, or alternatively expose a `DoWithContext` which seems to be the convention.

What do you think?

**Comment by odeke-em** [comment]
Hello @johanbrandhorst, thank you for the suggestion! Sounds like a plan and thank you for the kind words and for the PR implementing it.
